import pandas as pd
import numpy as np
from statsmodels.nonparametric.smoothers_lowess import lowess
import argparse


def make_npy(tsv_path, label, resolution):
    expected = pd.read_csv(tsv_path, sep="\t")

    expectedsum = expected.groupby(["diag"]).agg({"n_valid": "sum", "balanced.sum": "sum"})
    expectedsum["balanced.avg"] = expectedsum["balanced.sum"] / expectedsum["n_valid"]

    v = np.log(expectedsum["balanced.avg"].values)
    v = v[2: np.min(np.argwhere(~np.isfinite(v[2:])))]
    sv0 = lowess(
        v[int(48 / (resolution)) :], np.log(np.arange(int(48 / (resolution)), len(v)) + 1), frac=0.01
    )[:, 1]
    sv2 = lowess(
        v[int(48 / (resolution)) :], np.log(np.arange(int(48 / (resolution)), len(v)) + 1), frac=0.1
    )[:, 1]
    sv = np.hstack(
        [
            v[: int(48 / (resolution))],
            sv0[: int(48 / (resolution))],
            sv2[int(48 / (resolution)) :],
        ]
    )
    np.save(arr=sv, file=f"{label}_exp_{resolution}.npy")

parser = argparse.ArgumentParser()
parser.add_argument('tsv_path', type=str, help='Path to generated by cooltools .tsv file')
parser.add_argument('label', type=str, help='Label for the whole data')
parser.add_argument('resolution', type=int, help='Current resolution to calc for')

args = parser.parse_args()

make_npy(args.tsv_path, args.label, int(args.resolution))