name: calculate_expected_env
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.0.1
  - pip:
    - Cython==3.0.11
    - cooler==0.10.2
    - cycler==0.12.1
    - cytoolz==1.1.0
    - numpy==1.26.4
    - pandas==2.3.3

